version: '3'
services:
  solr:
    image: solr
    environment:
      - SOLR_MODULES=analysis-extras
    ports:
     - "8983:8983"
    volumes:
      - ./solr/configset:/var/solr/configsets/dialogs
      - data:/var/solr
    command: solr-create -c dialogs -d /var/solr/configsets/dialogs
  streamlit:
    build: streamlit
    volumes:
      - ./streamlit:/app
    ports:
      - "80:80"
volumes:
  data:
