version: '3'
services:
  solr:
    image: solr
    environment:
      - SOLR_MODULES=analysis-extras
    ports:
     - "8983:8983"
    volumes:
      - ./solr/configset:/var/solr/configsets/dialogs
      - data:/var/solr
    command: solr-create -c dialogs -d /var/solr/configsets/dialogs
  streamlit:
    build: .
    entrypoint: ["python", "-m", "streamlit", "run", "streamlit/app.py", "--server.port=80", "--server.address=0.0.0.0"]
    volumes:
      - .:/app
      - models:/models
    ports:
      - "80:80"
    environment:
      TRANSFORMERS_CACHE: /models
  work:
    build: .
    volumes:
      - ./data:/data
      - .:/app
      - models:/models
    environment:
      TRANSFORMERS_CACHE: /models
volumes:
  data:
  models:
